import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectRoot = path.join(__dirname, '..');
const srcDir = path.join(projectRoot, 'src');
const indexHtml = path.join(projectRoot, 'index.html');
const iconsDir = path.join(projectRoot, 'node_modules', 'bootstrap-icons', 'icons');
const outputCss = path.join(srcDir, 'styles', 'bootstrap-icons-subset.css');

// Find all .vue and .html files
function getFiles(dir, files = []) {
  const fileList = fs.readdirSync(dir);
  for (const file of fileList) {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      getFiles(fullPath, files);
    } else if (fullPath.endsWith('.vue') || fullPath.endsWith('.html') || fullPath.endsWith('.js')) {
      files.push(fullPath);
    }
  }
  return files;
}

const allFiles = getFiles(srcDir);
allFiles.push(indexHtml);

const biRegex = /\bbi-([a-z0-9-]+)\b/g;
const usedIcons = new Set();

for (const file of allFiles) {
  const content = fs.readFileSync(file, 'utf-8');
  let match;
  while ((match = biRegex.exec(content)) !== null) {
    usedIcons.add(match[1]);
  }
}

const validIcons = [];
for (const icon of usedIcons) {
  const svgPath = path.join(iconsDir, `${icon}.svg`);
  if (fs.existsSync(svgPath)) {
    validIcons.push(icon);
  }
}

let cssContent = `/* Subset of Bootstrap Icons generated by subset-icons.js */
.bi {
  display: inline-block;
  width: 1em;
  height: 1em;
  vertical-align: -0.125em;
  background-color: currentColor;
  -webkit-mask-size: 100% 100%;
  mask-size: 100% 100%;
}
`;

for (const icon of validIcons) {
  const svgPath = path.join(iconsDir, `${icon}.svg`);
  let svgContent = fs.readFileSync(svgPath, 'utf-8');
  
  const encodedSvg = svgContent
    .replace(/"/g, "'")
    .replace(/%/g, '%25')
    .replace(/#/g, '%23')
    .replace(/</g, '%3C')
    .replace(/>/g, '%3E')
    .replace(/\s+/g, ' ');

  cssContent += `
.bi-${icon} {
  -webkit-mask-image: url("data:image/svg+xml,${encodedSvg}");
  mask-image: url("data:image/svg+xml,${encodedSvg}");
}
`;
}

fs.writeFileSync(outputCss, cssContent);
console.log(`Generated subset CSS with ${validIcons.length} icons at ${outputCss}`);
